# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" GREATER 2.4)
  # Information for CMake 2.6 and above.
  set("teem_LIB_DEPENDS" "general;C:/Users/Nate/Anaconda3/Library/lib/z.lib;general;C:/Users/Nate/Anaconda3/Library/lib/libpng.lib;general;C:/Users/Nate/Anaconda3/Library/lib/z.lib;")
else()
  # Information for CMake 2.4 and lower.
  set("teem_LIB_DEPENDS" "C:/Users/Nate/Anaconda3/Library/lib/z.lib;C:/Users/Nate/Anaconda3/Library/lib/libpng.lib;C:/Users/Nate/Anaconda3/Library/lib/z.lib;")
endif()
